# Generated by Django 3.0 on 2019-12-18 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.TextField()),
                ('display_name', models.TextField()),
                ('initial_amount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('default', models.CharField(blank=True, choices=[('s', 'Source'), ('t', 'Target'), (None, 'Null')], default=None, max_length=1, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', related_query_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.TextField()),
                ('default', models.BooleanField(default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payees', related_query_name='payee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('narration', models.TextField(blank=True)),
                ('flag', models.CharField(choices=[('!', '!'), ('*', '*')], default='!', max_length=1)),
                ('keyword', models.TextField()),
                ('payee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.Payee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', related_query_name='template', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('narration', models.TextField(blank=True)),
                ('flag', models.CharField(choices=[('!', '!'), ('*', '*')], default='!', max_length=1)),
                ('payee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.Payee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', related_query_name='transaction', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostingTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('explicit', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.Account')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postings', related_query_name='posting', to='ledger.TransactionTemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('explicit', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.Account')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postings', related_query_name='posting', to='ledger.Transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='transactiontemplate',
            index=models.Index(fields=['user', '-date', '-created_at'], name='ledger_tran_user_id_192200_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transactiontemplate',
            unique_together={('user', 'keyword')},
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', '-date', '-created_at'], name='ledger_tran_user_id_fc192e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payee',
            unique_together={('user', 'default')},
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['user', 'name'], name='ledger_acco_user_id_c72f7d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('user', 'default')},
        ),
    ]
